# Generated by Django 4.1.7 on 2023-03-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gagaga_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.TextField(max_length=250, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='gagaga',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
