# Generated by Django 4.1.7 on 2023-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_application_comment_alter_gagaga_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В работе'), (2, 'Обработан')], verbose_name='Статус'),
        ),
    ]
