# Generated by Django 4.1.7 on 2023-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В работе'), (2, 'Обработан')], default=1, verbose_name='Статус'),
        ),
    ]
